import { FooterSection, NavComponent } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Ubuntu } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto bg-[#e4f4f7] xs:w-[100vw] sm:w-[100vw] md:w-[70vw]">
          <NavComponent />
          {children}
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
